# Generated by Django 4.2.4 on 2023-08-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CentreSante",
            fields=[
                ("id_centre", models.IntegerField(primary_key=True, serialize=False)),
                ("nom_centre", models.CharField(max_length=255)),
                ("emplacement", models.CharField(max_length=255)),
                ("service", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Declaration",
            fields=[
                (
                    "id_declaration",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nom_pr_declare", models.CharField(max_length=255)),
                ("sexe_declare", models.CharField(max_length=10)),
                ("fonct_declare", models.CharField(blank=True, max_length=50)),
                ("date_naiss", models.DateField()),
                ("date_deces", models.DateField()),
                ("mode_declaration", models.CharField(max_length=255)),
                ("raison_deces", models.CharField(blank=True, max_length=255)),
                ("nom_pr_parent", models.CharField(max_length=255)),
                ("lieu_habit", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Deplacement",
            fields=[
                (
                    "id_deplacement",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nom_pr_deplace", models.CharField(max_length=255)),
                ("sexe_deplace", models.CharField(max_length=10)),
                ("fonct_deplace", models.CharField(blank=True, max_length=50)),
                ("date_naissance", models.DateField()),
                ("provenance", models.CharField(max_length=50)),
                ("mode_heberg", models.CharField(max_length=50)),
                ("lieu_habit", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Maladie",
            fields=[
                ("id_maladie", models.IntegerField(primary_key=True, serialize=False)),
                ("nom_maladie", models.CharField(max_length=255)),
                ("periode_maladie", models.DateField()),
                ("des_maladie", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacie",
            fields=[
                (
                    "id_pharmacie",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("nom_pharmacie", models.CharField(max_length=255)),
                ("emplacement", models.CharField(max_length=255)),
                ("periode_garde", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Projets",
            fields=[
                ("id_projet", models.IntegerField(primary_key=True, serialize=False)),
                ("domaine_projet", models.CharField(max_length=255)),
                ("des_projet", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RechercheEmploi",
            fields=[
                ("id_offre", models.IntegerField(primary_key=True, serialize=False)),
                ("nom_pr", models.CharField(max_length=255)),
                ("service", models.CharField(max_length=255)),
                ("competence", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=50)),
                ("photo", models.ImageField(blank=True, upload_to="recherche_emploi/")),
                ("message", models.CharField(max_length=255)),
            ],
        ),
    ]
